-- ==============================================================================
-- CHALO DAAN KARE (चलो दान करें) - SUPABASE DATABASE SCHEMA
-- ==============================================================================
-- Instructions:
-- 1. Go to your Supabase Project Dashboard (https://supabase.com/dashboard)
-- 2. Click on "SQL Editor" from the left menu.
-- 3. Click "+ New query", paste this entire script, and click "RUN".
-- ==============================================================================

-- 1. Table for Crowdfunding Campaigns (इलाज, शिक्षा, NGO, पशु सेवा आदि)
create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  organizer text not null,
  place text not null,
  title text not null,
  category text not null,
  goal numeric not null default 0,
  story text not null,
  phone text default '',
  animal_type text default '',
  animal_purpose text default '',
  animal_organization text default '',
  animal_needs text default '',
  documents_info text default '',
  status text default 'pending' -- 'pending', 'approved', 'completed', 'rejected'
);

-- 2. Table for Physical Item Donations (कपड़े, किताबें, खिलौने, राशन आदि)
create table if not exists public.donation_offers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  donor_name text not null,
  phone text not null,
  place text not null,
  category text not null,
  items_description text not null,
  pickup_type text default 'Donor will drop / Volunteer pickup',
  status text default 'available' -- 'available', 'collected', 'delivered'
);

-- 3. Enable Row Level Security (RLS)
alter table public.campaigns enable row level security;
alter table public.donation_offers enable row level security;

-- 4. Policies to allow public visitors to submit data and view approved records
-- Campaigns policies
drop policy if exists "Allow anyone to submit campaigns" on public.campaigns;
create policy "Allow anyone to submit campaigns" 
  on public.campaigns for insert with check (true);

drop policy if exists "Allow anyone to read campaigns" on public.campaigns;
create policy "Allow anyone to read campaigns" 
  on public.campaigns for select using (true);

drop policy if exists "Allow client to update campaigns" on public.campaigns;
create policy "Allow client to update campaigns" 
  on public.campaigns for update using (true);

drop policy if exists "Allow client to delete campaigns" on public.campaigns;
create policy "Allow client to delete campaigns" 
  on public.campaigns for delete using (true);

-- Donation Offers policies
drop policy if exists "Allow anyone to submit donation offers" on public.donation_offers;
create policy "Allow anyone to submit donation offers" 
  on public.donation_offers for insert with check (true);

drop policy if exists "Allow anyone to read donation offers" on public.donation_offers;
create policy "Allow anyone to read donation offers" 
  on public.donation_offers for select using (true);

drop policy if exists "Allow client to update donation offers" on public.donation_offers;
create policy "Allow client to update donation offers" 
  on public.donation_offers for update using (true);

drop policy if exists "Allow client to delete donation offers" on public.donation_offers;
create policy "Allow client to delete donation offers" 
  on public.donation_offers for delete using (true);

-- ==============================================================================
-- CLEANUP / PURGE DEMO RECORDS (Optional - Run if you want to wipe demo data)
-- ==============================================================================
-- TRUNCATE TABLE public.campaigns, public.donation_offers;
