-- ==============================================================================
-- CHALO DAAN KARE (चलो दान करें) - SUPABASE DATABASE SCHEMA
-- ==============================================================================
-- Instructions:
-- 1. Go to your Supabase Project Dashboard (https://supabase.com/dashboard)
-- 2. Click on "SQL Editor" from the left menu.
-- 3. Click "+ New query", paste this entire script, and click "RUN".
-- ==============================================================================

-- 1. Table for Crowdfunding Campaigns (इलाज, शिक्षा, NGO, पशु सेवा आदि)
create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  organizer text not null,
  place text not null,
  title text not null,
  category text not null,
  goal numeric not null default 0,
  story text not null,
  phone text default '',
  animal_type text default '',
  animal_purpose text default '',
  animal_organization text default '',
  animal_needs text default '',
  documents_info text default '',
  status text default 'pending' -- 'pending', 'approved', 'completed', 'rejected'
);

-- 2. Table for Physical Item Donations (कपड़े, किताबें, खिलौने, राशन आदि)
create table if not exists public.donation_offers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  donor_name text not null,
  phone text not null,
  place text not null,
  category text not null,
  items_description text not null,
  pickup_type text default 'Donor will drop / Volunteer pickup',
  status text default 'available' -- 'available', 'collected', 'delivered'
);

-- 3. Enable Row Level Security (RLS)
alter table public.campaigns enable row level security;
alter table public.donation_offers enable row level security;

-- 4. Policies to allow public visitors to submit data and view approved records
-- Campaigns policies
create policy "Allow anyone to submit campaigns" 
  on public.campaigns for insert with check (true);

create policy "Allow anyone to read campaigns" 
  on public.campaigns for select using (true);

create policy "Allow client to update campaigns" 
  on public.campaigns for update using (true);

create policy "Allow client to delete campaigns" 
  on public.campaigns for delete using (true);

-- Donation Offers policies
create policy "Allow anyone to submit donation offers" 
  on public.donation_offers for insert with check (true);

create policy "Allow anyone to read donation offers" 
  on public.donation_offers for select using (true);

create policy "Allow client to update donation offers" 
  on public.donation_offers for update using (true);

create policy "Allow client to delete donation offers" 
  on public.donation_offers for delete using (true);

-- ==============================================================================
-- Sample initial test data (Optional)
-- ==============================================================================
insert into public.campaigns (organizer, place, title, category, goal, story, status)
values 
  ('Dr. Rajesh Sharma', 'Mumbai Central', 'Help Meera take her next step', 'Medical', 500000, 'Support Meera recovery and rehabilitation journey after accidental injury.', 'approved'),
  ('Vidyadaan Trust', 'Mulund', 'A new school year full of possibilities', 'Education', 200000, 'Providing school kits, notebooks and tuition fee support for 50 children.', 'approved'),
  ('Karuna Animal Care', 'Thane', 'Emergency Medical & Food Care for 40 Stray Dogs', 'Animal Welfare', 120000, 'Daily feeding, rabies vaccination and winter bedding in Wagle Estate area.', 'approved');

insert into public.donation_offers (donor_name, phone, place, category, items_description, status)
values
  ('Kavita Sharma', '9820011223', 'Thane West', 'Books & Stationery', 'Class 8-10 CBSE textbooks and unused notebooks in great condition.', 'available'),
  ('Rahul Mehta', '9819922334', 'Dadar, Mumbai', 'Clothes, Footwear & Blanket', '15 warm blankets and clean winter clothes for elderly and kids.', 'available');
